<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Very weak - Please enter a stronger password</name>
   <tag></tag>
   <elementGuidId>80c26556-b8e4-4819-afc3-dc566a480875</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.woocommerce-password-strength.short</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='customer_login']/div[2]/form/p[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Very weak - Please enter a stronger password.&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>dc656e4c-ffde-4061-9879-b19898b18646</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>woocommerce-password-strength short</value>
      <webElementGuid>57eaf5a5-1330-4d36-8783-59b31ca8032a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-live</name>
      <type>Main</type>
      <value>polite</value>
      <webElementGuid>2a1344fb-0d45-4ddc-9948-f74300da894e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Very weak - Please enter a stronger password.</value>
      <webElementGuid>b66aa774-765b-427b-b4d6-78bc83ab1325</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;customer_login&quot;)/div[@class=&quot;u-column2 col-2&quot;]/form[@class=&quot;register&quot;]/p[@class=&quot;woocommerce-FormRow woocommerce-FormRow--wide form-row form-row-wide&quot;]/div[@class=&quot;woocommerce-password-strength short&quot;]</value>
      <webElementGuid>cd2a1f34-4d6a-4013-8a9c-660690303070</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='customer_login']/div[2]/form/p[2]/div</value>
      <webElementGuid>dc5df8d1-09df-4a80-b3eb-3f06f7cd712b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[4]/following::div[1]</value>
      <webElementGuid>8b031afb-7b1b-4acb-98e0-76e0ac636a09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Anti-spam'])[1]/preceding::div[1]</value>
      <webElementGuid>e5dd0170-ba05-4a50-8a6f-af4ad9e5cdb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Subscribe Here'])[1]/preceding::div[19]</value>
      <webElementGuid>4d6ff864-6816-42e0-80ef-396301239c99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Very weak - Please enter a stronger password.']/parent::*</value>
      <webElementGuid>99634bf4-c663-49d5-ba43-3a6bdb6678c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[2]/div</value>
      <webElementGuid>8a9192a9-3947-48f8-adb6-b8302ad8c08f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Very weak - Please enter a stronger password.' or . = 'Very weak - Please enter a stronger password.')]</value>
      <webElementGuid>4fb2660f-2db0-4308-b9a5-d8d68d1ad74e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
