<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Automation Testing</name>
   <tag></tag>
   <elementGuidId>817f4245-5471-4c84-bbbb-44957c129fd8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='site-description']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.google-anno-t</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Automation Testing&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>da5823fd-1777-4d0c-88ef-9ba577285484</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>google-anno-t</value>
      <webElementGuid>bd99bdfc-fef0-4aee-9c1e-dff1ffc3ab0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Automation Testing</value>
      <webElementGuid>90e45458-e995-4bb9-956d-e3219207ec14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;site-description&quot;)/span[1]/a[@class=&quot;google-anno&quot;]/span[@class=&quot;google-anno-t&quot;]</value>
      <webElementGuid>25bd7ace-75c7-485a-b279-84f27f09494d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='site-description']/span/a/span</value>
      <webElementGuid>64ffb90b-351e-4410-98b0-e838aaab824c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Selenium Webdriver Appium Complete Tutorial'])[1]/following::span[2]</value>
      <webElementGuid>ca26c69d-77b5-466e-8744-fe41ee7cda05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tools'])[1]/preceding::span[1]</value>
      <webElementGuid>600b5d60-e617-4281-93ac-9b30d4a24706</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Selenium Java Tutorial'])[1]/preceding::span[3]</value>
      <webElementGuid>cbc57616-0b38-427f-8777-cea07b624899</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Automation Testing']/parent::*</value>
      <webElementGuid>0e17da1c-578f-4b11-a87e-bc8dd5854d68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/a/span</value>
      <webElementGuid>d90ed5b0-e305-4601-94ff-5e6021fb67d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Automation Testing' or . = 'Automation Testing')]</value>
      <webElementGuid>fced8993-94cf-4999-83b2-664740a3d7ab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
