<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_JavaScript</name>
   <tag></tag>
   <elementGuidId>07e46ba7-9b05-44df-bd32-06dc3367afc1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.cat-item.cat-item-21 > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='woocommerce_product_categories-2']/ul/li[3]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;JavaScript&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1c57f1a5-e572-4c07-80a7-04a326fcb55b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://practice.automationtesting.in/product-category/javascript/</value>
      <webElementGuid>a0aee97e-4578-4ae5-b287-de69d8879b2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>JavaScript</value>
      <webElementGuid>6429fc73-afcd-4d7d-bd02-b212f1174197</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;woocommerce_product_categories-2&quot;)/ul[@class=&quot;product-categories&quot;]/li[@class=&quot;cat-item cat-item-21&quot;]/a[1]</value>
      <webElementGuid>4e3d48f0-66ff-4a50-966c-9b092d730c14</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='woocommerce_product_categories-2']/ul/li[3]/a</value>
      <webElementGuid>65e3aadc-10c5-4ca4-96cb-9387cc3c5c38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'JavaScript')]</value>
      <webElementGuid>b7d71b54-8cd1-4aa6-86f9-053974e76e5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(3)'])[1]/following::a[1]</value>
      <webElementGuid>9aedcaaa-70ca-4309-97ce-17bafa491230</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HTML'])[1]/following::a[1]</value>
      <webElementGuid>72673911-b3a9-4edb-83e6-6d65047441fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(3)'])[2]/preceding::a[1]</value>
      <webElementGuid>6dbd3f70-2cf6-492d-8efe-d7a6fe4fdb2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='selenium'])[1]/preceding::a[1]</value>
      <webElementGuid>d23266ea-65da-47b5-ba6f-9725492c6bd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='JavaScript']/parent::*</value>
      <webElementGuid>63c81269-f735-4497-a1a9-b9ebc70574ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://practice.automationtesting.in/product-category/javascript/')]</value>
      <webElementGuid>7c4de23b-a4db-4b19-bf63-30c4bc9382ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/ul/li[3]/a</value>
      <webElementGuid>4f25b5e7-21af-4bd2-bc62-9949a7b781a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://practice.automationtesting.in/product-category/javascript/' and (text() = 'JavaScript' or . = 'JavaScript')]</value>
      <webElementGuid>fb20476f-2be5-42f9-9e1d-c681965a3220</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
