<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_AutoComplete</name>
   <tag></tag>
   <elementGuidId>731487d7-1868-4a67-8094-75add5f16547</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='header']/nav/div/div[2]/ul/li[5]/ul/li[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.dropdown.open > ul.dropdown-menu > li:nth-of-type(2) > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;AutoComplete&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d845857f-08b3-41b0-8938-5ed48fd387da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>AutoComplete.html</value>
      <webElementGuid>65ba6656-0178-4b93-aab6-c7410ba62a56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> AutoComplete </value>
      <webElementGuid>13581be0-751a-4618-9e4f-2d7451ce3e99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header&quot;)/nav[@class=&quot;navbar navbar-inverse&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;navbar-collapse collapse navbar-right&quot;]/ul[@class=&quot;nav navbar-nav&quot;]/li[@class=&quot;dropdown  open&quot;]/ul[@class=&quot;dropdown-menu&quot;]/li[2]/a[1]</value>
      <webElementGuid>1e00eea0-4912-450f-bcdb-2059e6e62b53</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='header']/nav/div/div[2]/ul/li[5]/ul/li[2]/a</value>
      <webElementGuid>e32ac084-8d1d-4190-8fc5-92bfa536047d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'AutoComplete')]</value>
      <webElementGuid>2bdbcaf9-ce53-4586-b55f-d129a0cf5485</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Accordion'])[1]/following::a[1]</value>
      <webElementGuid>49ed5e0d-af50-4c63-ba37-10740018be30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Widgets'])[1]/following::a[2]</value>
      <webElementGuid>9a61f3c3-44bc-41aa-b42d-f20985e4ae43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Datepicker'])[1]/preceding::a[1]</value>
      <webElementGuid>518544b9-28db-4bc9-bbcf-272585b59039</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Slider'])[1]/preceding::a[2]</value>
      <webElementGuid>46e4eaa0-c529-4bcc-ad1d-3efe6e854bb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='AutoComplete']/parent::*</value>
      <webElementGuid>551d21c0-90fd-4e16-ba86-0c94d6dc2afb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'AutoComplete.html')]</value>
      <webElementGuid>1ea01b31-7d16-4fdd-bf97-b75b931c1b8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/ul/li[2]/a</value>
      <webElementGuid>e5311f74-35da-4754-b29f-ee45ac29fbe5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'AutoComplete.html' and (text() = ' AutoComplete ' or . = ' AutoComplete ')]</value>
      <webElementGuid>9c6fcf09-3a2c-4733-80ba-9bec6b678217</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
