<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Alerts</name>
   <tag></tag>
   <elementGuidId>1a1ad7c2-d1a8-443e-a4c9-0eac7f4d2b71</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='header']/nav/div/div[2]/ul/li[4]/ul/li/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>ul.dropdown-menu > li > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Alerts&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b2befdd8-0acf-4903-8f65-cadd70dde09d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>Alerts.html</value>
      <webElementGuid>f81d60f8-1b0b-4105-8a90-a4252a10ee26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Alerts</value>
      <webElementGuid>2091ccab-4c6f-4c72-bff9-1f120118d018</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header&quot;)/nav[@class=&quot;navbar navbar-inverse&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;navbar-collapse collapse navbar-right&quot;]/ul[@class=&quot;nav navbar-nav&quot;]/li[@class=&quot;dropdown active open&quot;]/ul[@class=&quot;dropdown-menu&quot;]/li[1]/a[1]</value>
      <webElementGuid>7774dd95-a05b-4fc6-8194-d3246adbd8bd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='header']/nav/div/div[2]/ul/li[4]/ul/li/a</value>
      <webElementGuid>9692a4a9-dad6-4839-a0dc-94ff8a810e1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Alerts')]</value>
      <webElementGuid>6c7f966e-e787-4597-8c04-d8c244d9a317</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SwitchTo'])[1]/following::a[1]</value>
      <webElementGuid>44b9bcf2-a493-4543-8772-e0e5efcf1618</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='WebTable'])[1]/following::a[2]</value>
      <webElementGuid>7b5628dc-f09d-42e4-8b91-5cff7b6c6f9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Windows'])[1]/preceding::a[1]</value>
      <webElementGuid>ac1163b3-a09c-453e-a15b-19ecfd429425</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Frames'])[1]/preceding::a[2]</value>
      <webElementGuid>b077bb34-7b99-4da1-b4f3-d5fcf784af4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'Alerts.html')]</value>
      <webElementGuid>e91e7c88-42eb-47d0-823a-c0a683863874</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/ul/li/a</value>
      <webElementGuid>3b333226-6929-4c4b-bc2b-67f717cba65c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'Alerts.html' and (text() = 'Alerts' or . = 'Alerts')]</value>
      <webElementGuid>a0fbaa95-41b7-4c45-a841-f079a8de836e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
