name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Katalon Studio Github Action
      uses: katalon-studio/katalon-studio-github-action@v2.1
      with:
          version: '9.7.2'
          projectPath: '${{ github.workspace }}'
          args: './katalonc -noSplash -runMode=console -projectPath="/Users/nhan.hoang/Documents/nhanhoanganh-katalon-cert/nhanhoanganh-katalon-cert.prj" -retry=0 -testSuitePath="Test Suites/TS_03" -browserType="Chrome" -executionProfile="default" -apiKey="37bb3e8b-0142-48db-9706-225fec0f35fb" -orgID=1655112 -testOpsProjectId=1631721 --config -webui.autoUpdateDrivers=true'
