name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Katalon Studio Github Action
      uses: katalon-studio/katalon-studio-github-action@v2.1
      with:
          version: '9.7.2'
          projectPath: '${{ github.workspace }}'
          args: '-noSplash -runMode=console -retry=0 -testSuitePath="Test Suites/TS_03" -browserType="Chrome" -executionProfile="default" -apiKey=${{ secrets.katalon_api_key}} -orgID=1655112 -testOpsProjectId=1631721 --config -webui.autoUpdateDrivers=true'
