<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_1_1</name>
   <tag></tag>
   <elementGuidId>b37f3396-9d61-42b0-96d4-0f0e0798894b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tr[@id='product-2']/td[4]/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#product-2 > td.cart_quantity > button.disabled</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;Product Image Men Tshirt Men > Tshirts Rs. 400 1 Rs. 400 &quot;i] >> internal:role=button</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5da51be6-fd08-4598-967e-2f2dbdfe67b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>disabled</value>
      <webElementGuid>0e28b04b-e301-4df0-8bb3-f87792bff358</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>00a61399-32a9-4583-8ebb-2717f5153ceb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product-2&quot;)/td[@class=&quot;cart_quantity&quot;]/button[@class=&quot;disabled&quot;]</value>
      <webElementGuid>b49b3b72-f218-4fd3-9e25-837b217a6018</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='product-2']/td[4]/button</value>
      <webElementGuid>1436a64e-a146-46de-abd8-07dd464d80c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Men Tshirt'])[1]/following::button[1]</value>
      <webElementGuid>012c3fdf-4831-4625-aa46-978a003b36aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Blue Top'])[1]/following::button[2]</value>
      <webElementGuid>a913a2c1-8c69-4f42-b265-a95552ba687d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cart is empty!'])[1]/preceding::button[1]</value>
      <webElementGuid>f7a4da57-228f-4965-b306-8447309adc92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='here'])[1]/preceding::button[1]</value>
      <webElementGuid>d03f3c26-bd25-4c3e-a295-7412515cbaaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[4]/button</value>
      <webElementGuid>07a557d8-b21b-486d-811f-c5ab8d83db20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = '1' or . = '1')]</value>
      <webElementGuid>eed13234-615d-4d47-acfa-bace5396b32f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
